### ISSUE TITLE
Attention_block cause tuple index out of range

### ISSUE THREAD

**Issue by FangYang970206** [graykode/modelsummary#1]
When I used  `summary` to list my model with Attention_block, the bug occurred. Here is test code, run it,  can reproduce the bug.
```python
import torch
import torch.nn as nn


class Attention_block(nn.Module):
    def __init__(self, F_g, F_l, F_int):
        super(Attention_block, self).__init__()
        self.W_g = nn.Sequential(
            nn.Conv2d(
                F_g, F_int, kernel_size=1, stride=1, padding=0, bias=True),
            nn.BatchNorm2d(F_int))

        self.W_x = nn.Sequential(
            nn.Conv2d(
                F_l, F_int, kernel_size=1, stride=1, padding=0, bias=True),
            nn.BatchNorm2d(F_int))

        self.psi = nn.Sequential(
            nn.Conv2d(F_int, 1, kernel_size=1, stride=1, padding=0, bias=True),
            nn.BatchNorm2d(1), nn.Sigmoid())

        self.relu = nn.LeakyReLU(inplace=True)

    def forward(self, g, x):
        g1 = self.W_g(g)
        x1 = self.W_x(x)
        psi = self.relu(g1 + x1)
        psi = self.psi(psi)

        return x * psi


class Shader(nn.Module):
    def __init__(self):
        super(Shader, self).__init__()
        self.att1 = Attention_block(16, 16, 8)
        self.conv1 = nn.Conv2d(3, 16, 3, 1, 1)
        self.conv2 = nn.Conv2d(3, 16, 3, 1, 1)

    def forward(self, inp):
        x1 = self.conv1(inp)
        x2 = self.conv2(inp)
        out = self.att1(g=x1, x=x2)
        return out


if __name__ == "__main__":
    from modelsummary import summary
    model = Shader()
    inp = torch.randn(4, 3, 16, 16)
    output = model.forward(inp)
    print('forward success!')
    summary(model, inp)
```

The bug is followed:
```bash
(root) C:\Users\fangyang\Desktop\bug>python test.py
forward success!
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    summary(model, inp)
  File "D:\Anaconda3\lib\site-packages\modelsummary\modelsummary.py", line 66, in summary
    model(*inputs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "test.py", line 43, in forward
    out = self.att1(g=x1, x=x2)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 485, in __call__
    hook(self, input)
  File "D:\Anaconda3\lib\site-packages\modelsummary\modelsummary.py", line 28, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
IndexError: tuple index out of range
```

**Comment by ryujaehun** [comment]
I had a similar experience in edsr model.

```
class EDSR(nn.Module):
    def __init__(self, args, conv=common.default_conv):
        super(EDSR, self).__init__()

        n_resblocks = args.n_resblocks
        n_feats = args.n_feats
        kernel_size = 3 
        scale = args.scale[0]
        act = nn.ReLU(True)
        self.url = url['r{}f{}x{}'.format(n_resblocks, n_feats, scale)]
        self.sub_mean = common.MeanShift(args.rgb_range)
        self.add_mean = common.MeanShift(args.rgb_range, sign=1)

        # define head module
        m_head = [conv(args.n_colors, n_feats, kernel_size)]

        # define body module
        m_body = [
            common.ResBlock(
                conv, n_feats, kernel_size, act=act, res_scale=args.res_scale
            ) for _ in range(n_resblocks)
        ]
        m_body.append(conv(n_feats, n_feats, kernel_size))

        # define tail module
        m_tail = [
            common.Upsampler(conv, scale, n_feats, act=False),
            conv(n_feats, args.n_colors, kernel_size)
        ]

        self.head = nn.Sequential(*m_head)
        self.body = nn.Sequential(*m_body)
        self.tail = nn.Sequential(*m_tail)

    def forward(self, x):
        x = self.sub_mean(x)
        x = self.head(x)

        res = self.body(x)
        res += x

        x = self.tail(res)
        x = self.add_mean(x)

        return x 
```


```
  File "test.py", line 5, in <module>
    summary(model, (64,3,256,256), show_input=True)
  File "/opt/conda/lib/python3.6/site-packages/modelsummary/modelsummary.py", line 66, in summary
    model(*inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/EDSR-PyTorch/src/model/edsr.py", line 42, in forward
    x = self.sub_mean(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 488, in __call__
    hook(self, input)
  File "/opt/conda/lib/python3.6/site-packages/modelsummary/modelsummary.py", line 28, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by graykode** [comment]
@FangYang970206 It's because of `Attention_block` which is not pytorch `nn`.
Output is not an issue, but when using the input option, it is an issue because input is null.
So I fixed 
```python
            if len(input) != 0 :
                summary[m_key]["input_shape"] = list(input[0].size())
                summary[m_key]["input_shape"][0] = batch_size
            else:
                summary[m_key]["input_shape"] = input
```
